import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

test('cart page uses selection controls and adapts single recommendations to full width', () => {
  const wxml = fs.readFileSync(path.join(__dirname, '../pages/cart/index.wxml'), 'utf8')
  const wxss = fs.readFileSync(path.join(__dirname, '../pages/cart/index.wxss'), 'utf8')

  assert.match(wxml, /class="\{\{item\.checkClass\}\}"/)
  assert.match(wxml, /class="cart-check-dot"/)
  assert.match(wxml, /class="media-shell"/)
  assert.match(wxml, /class="cover-badge"/)
  assert.match(wxml, /class="feature-row"/)
  assert.match(wxml, /class="feature-chip feature-chip-primary"/)
  assert.match(wxml, /class="card-footer"/)
  assert.match(wxml, /class="stepper-shell"/)
  assert.match(wxml, /class="select-all"/)
  assert.match(wxml, /class="recommend-section"/)
  assert.match(wxml, /class="\{\{recommendGridClass\}\}"/)
  assert.match(wxml, /class="secure-row"/)
  assert.doesNotMatch(wxml, /class="summary"/)
  assert.doesNotMatch(wxml, /class="price-caption"/)
  assert.doesNotMatch(wxml, /class="option-pill"/)
  assert.doesNotMatch(wxml, /button class="step-button"/)

  assert.match(wxss, /\.cart-card\s*\{[\s\S]*padding:\s*20rpx 18rpx;/)
  assert.match(wxss, /\.cart-card\s*\{[\s\S]*border-radius:\s*22rpx;/)
  assert.match(wxss, /\.cart-card\s*\{[\s\S]*background:\s*#ffffff;/)
  assert.match(wxss, /\.cart-card\s*\{[\s\S]*grid-template-columns:\s*auto 148rpx minmax\(0,\s*1fr\);/)
  assert.match(wxss, /\.card-select\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(wxss, /\.cart-check-dot\s*\{[\s\S]*width:\s*12rpx;/)
  assert.match(wxss, /\.cover\s*\{[\s\S]*width:\s*148rpx;/)
  assert.match(wxss, /\.cover\s*\{[\s\S]*height:\s*148rpx;/)
  assert.match(wxss, /\.cover\s*\{[\s\S]*border-radius:\s*16rpx;/)
  assert.match(wxss, /\.card-body\s*\{[\s\S]*min-height:\s*148rpx;/)
  assert.doesNotMatch(wxss, /\.card-body\s*\{[\s\S]*padding-right:\s*70rpx;/)
  assert.match(wxss, /\.card-top\s*\{[\s\S]*display:\s*flex;/)
  assert.match(wxss, /\.card-top\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.doesNotMatch(wxss, /\.delete-link\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(wxss, /\.delete-link\s*\{[\s\S]*flex:\s*0 0 auto;/)
  assert.match(wxss, /\.feature-chip-primary\s*\{[\s\S]*background:\s*#fff2e8;/)
  assert.match(wxss, /\.card-footer\s*\{[\s\S]*margin-top:\s*auto;/)
  assert.match(wxss, /\.card-footer\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto;/)
  assert.match(wxss, /\.price-group\s*\{[\s\S]*display:\s*flex;/)
  assert.match(wxss, /\.unit-text\s*\{[\s\S]*margin-top:\s*0;/)
  assert.match(wxss, /\.stepper-shell\s*\{[\s\S]*border-radius:\s*999rpx;/)
  assert.match(wxss, /\.recommend-grid-single\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\);/)
  assert.match(wxss, /\.recommend-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/)
  assert.match(wxss, /\.checkout-bar\s*\{[\s\S]*left:\s*0;/)
  assert.match(wxss, /\.checkout-bar\s*\{[\s\S]*right:\s*0;/)
  assert.match(wxss, /\.checkout-bar\s*\{[\s\S]*bottom:\s*0;/)
  assert.match(wxss, /\.checkout-bar\s*\{[\s\S]*border-radius:\s*28rpx 28rpx 0 0;/)
  assert.match(wxss, /\.checkout-bar\s*\{[\s\S]*padding:\s*12rpx 24rpx;/)
  assert.match(wxss, /\.checkout-button\s*\{[\s\S]*height:\s*76rpx;/)
  assert.match(wxss, /\.stepper\s*\{[\s\S]*width:\s*176rpx;/)
})
